### ISSUE TITLE
Section: Iteration

### ISSUE THREAD

**Issue by markroepke** [uc-python/intermediate-python-datasci#6]

**Comment by markroepke** [comment]
Ready for review, @eswan18.

**Comment by eswan18** [comment]
I think a non-counting example would be a good supplement to the current examples here:
<img width="465" alt="image" src="https://user-images.githubusercontent.com/3449508/59568085-d149e400-9043-11e9-95b6-da8e9bf730cc.png">

Perhaps "Keep walking down this road until you hit 5th Street."

**Comment by eswan18** [comment]
This bit is very confusing, imo:
<img width="609" alt="image" src="https://user-images.githubusercontent.com/3449508/59568232-0eaf7100-9046-11e9-97c0-131bc5881d42.png">

I don't see any benefit in specifying `range(1, 10)` vs `range(10)` – in fact, it may be more confusing because students will only see 9 iterations. It would be simplest to go with the latter, even if the generated values are 0-9.

**Comment by eswan18** [comment]
Looks good beyond that

**Comment by markroepke** [comment]
Thanks, made fixes and ready for merge to develop.

**Comment by eswan18** [comment]
Merged
